admin_admin_homepage:
    path:     /hello/{name}
    defaults: { _controller: SuppliercheckAdminBundle:Default:index }
    
#admin_campaign:
#    path:     /supplier/suppliercheck/admin/campaign/{id}/product/list
#    defaults: { _controller: SuppliercheckAdminBundle:Default:index }
#    
#    


adminImportCSV:
     pattern:  /admin/dashbord/import
     defaults:  { _controller: SuppliercheckAdminBundle:CSV:importFile }
     
# app/config/routing.yml
#fos_user:
    #resource: "@FOSUserBundle/Resources/config/routing/all.xml"
#    
#fos_user_security:
#    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
#
#fos_user_profile:
#    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
#    prefix: /profile
#
#fos_user_register:
#    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
#    prefix: /register
#
#fos_user_resetting:
#    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
#    prefix: /reset
#
#fos_user_change_password:
#    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
#    prefix: /profil
    
sonata_user_security:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_security_1.xml"

sonata_user_resetting:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_resetting_1.xml"
    prefix: /resetting

sonata_user_profile:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_profile_1.xml"
    prefix: /profile

sonata_user_register:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_registration_1.xml"
    prefix: /register

sonata_user_change_password:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_change_password_1.xml"
    prefix: /profile