<?php

namespace Suppliercheck\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * campaignRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class campaignRepository extends EntityRepository
{
}
