Suppliercheck\AdminBundle\Entity\Comment:
    type: entity
    table: product_comment
    repositoryClass: Suppliercheck\AdminBundle\Entity\ProductRepository
    id:
      id:
        type: integer
        generator: { strategy: AUTO }
    fields:
      color:
        type: text
        length: 255
        nullable: true
      measures:
        type: text
        length: 255
        nullable: true
      description:
        type: text
        length: 255
        nullable: true  
      mainMaterial:
        type: text
        length: 255
        nullable: true 
      color:
        type: text
        length: 255
        nullable: true
      originalPrice:
        type: text
        length: 255
        nullable: true
      price:
        type: text
        length: 255
        nullable: true  
      netPurchasePrice:
        type: text
        length: 255
        nullable: true 
      name:
        type: text
        length: 255
        nullable: true 
               

               
    oneToOne:
      product:
        targetEntity: Product
        inversedBy: product_comment 
        joinColumn:
          name: product_id
          referencedColumnName: id       
                   
            
    lifecycleCallbacks: {  }